### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-T12-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T12-2/main#183]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @termehlee for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-2/main/issues/37 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @chaojieliu666 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-2/main/issues/148 https://github.com/AY1920S1-CS2113T-T12-2/main/issues/137 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @otonashixav for `v1.4`
* [ ] Merged updates to code (Java/FXML) files during the past 2 weeks (:exclamation:)
* [ ] Has issues assigned or PRs authored for `v1.4` milestone (:exclamation:)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @lucasfoo for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T12-2/main/issues/148 https://github.com/AY1920S1-CS2113T-T12-2/main/issues/57 https://github.com/AY1920S1-CS2113T-T12-2/main/issues/37 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @akshayeshenoi

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
